### ISSUE TITLE
Call not routing through, just shows "RING" then "ONHOOK" shortly after

### ISSUE THREAD

**Issue by phalkon13** [sladesys/LennyTroll#6]
I've gotten lenny-0.12 currently installed and running as a service.  
I have the recommended USRobotics USR5637 USB 56k modem, and it comes up properly.
I have my Lenny box connected to an IP Office 500v2 on current 11.1 software, and have tried the phone port on a Combo card (for digital phones, analog phones, and analog trunks) as well as a Phone8 card (for up to 8 analog phones).

When I call to the analog extension I have set up for this (with default settings) that is connected to the USB modem, it shows the status on the Lenny service change from "ONHOOK" to "RING" for a second or less, then goes back to "ONHOOK" and never shows as "RING" again or proceeds any further unless I stop and start the service.  I get the same results from running Lenny as an application instead of a service.

I have to stop Lenny (either via CRTL-C when running as app, or "sudo systemctl stop lenny" and then start again) before I get any more activity from the line at all, otherwise it acts like the line isn't even ringing.

Additionally, I would recommend allowing for an option in the configuration to configure how many rings before the device picks up (i.e. 1 ring, immedate, 4 rings, etc...).

Any help would be greatly appreciated.  If you need any logging, please let me know.  I am also going to copy/paste this to the  "Report a defect" via the webui, just in case.

**Comment by CiAntRawknis** [comment]
Did you find a solution for this?

I have the same issue

**Comment by CiAntRawknis** [comment]
The USR5637 ships with an older firmware which does not support voice. The solution is to update the firmware:
https://groups.io/g/callattendant/topic/usr5637_refuses_to_go_into/80708342
https://www.usr.com/en-support/product/?prod=5637

**Comment by phalkon13** [comment]
Thank you, I will try this when I get a chance.  Currently I ended up installing a Asterisk VM with the Lenny module on that, but I would like to have more of the customization that the RPi module gives.  I will try to update and test again in the next day or two, and will let you know my results.  Thank you for the information again.

**Comment by phalkon13** [comment]
Took a little longer, as I had originally wiped the SD card with Lenny installed and had to do it all over again (ended up having to install javascript-obvuscator via npm) but I got it working, and just like you said the Firmware update ended up fixing the issue (sadly, the firmware website is no longer available, but the Wayback Machine helped with that).

I would recommend to the creator of Lenny to possibly list the additional steps needed for getting this working properly on the website as well as possibly on here:

Install LibUSB and LibUDev (already listed here but not on website):
 sudo apt install libudev-dev libusb-dev 

Easy install of javascript-obfuscator:
 npm install --save-dev javascript-obfuscator

Upgrade of USR5637 modem to voice-supported firmware:
Wayback Machine direct link to USB Flasher from October 5 2022: [USRFlash](https://web.archive.org/web/20221005134543/https://support.usr.com/support/5637/5637-files/USRFlash%201.2.23.EXE)
Wayback Machine link to Support site from October 5 2022: [Support Link](https://web.archive.org/web/20221005134543/https://support.usr.com/support/product-template.asp?prod=5637)

Hope this helps anyone having issues, and thanks for the head's up on the firmware!
